(()=>{
  const book=document.getElementById('book'),cover=document.querySelector('.cover'),foreword=document.querySelector('.foreword'),sealPage=document.querySelector('.foreword-seal'),status=document.getElementById('status'),canvas=document.getElementById('glyph-overlay'),ctx=canvas.getContext('2d');
  let current=0,navigationLocked=false;
  function usableHeight(page){const cs=getComputedStyle(page);return page.clientHeight-(parseFloat(cs.paddingTop)||0)-(parseFloat(cs.paddingBottom)||0)}
  function pageFits(page){const inner=page.querySelector('.foreword-inner');return inner.scrollHeight<=usableHeight(page)+1}
  function makeContinuation(){const section=document.createElement('section');section.className='page foreword foreword-cont';section.setAttribute('aria-label','Foreword continued');const inner=document.createElement('div');inner.className='foreword-inner';const opening=document.createElement('div');opening.className='opening';inner.appendChild(opening);section.appendChild(inner);book.insertBefore(section,sealPage);return{section,opening}}
  function paginateForeword(){const firstOpening=foreword.querySelector('.opening'),items=[...firstOpening.children];firstOpening.innerHTML='';let page=foreword,opening=firstOpening;for(const item of items){opening.appendChild(item);if(!pageFits(page)){opening.removeChild(item);const next=makeContinuation();page=next.section;opening=next.opening;opening.appendChild(item)}}}
  paginateForeword();
  const pages=[...book.querySelectorAll('.page')],last=pages.length-1,sealIndex=pages.indexOf(sealPage),forewordPages=pages.map((p,i)=>({p,i})).filter(x=>x.p.classList.contains('foreword'));
  status.textContent=`1 / ${pages.length}`;
  const pf=new St.PageFlip(book,{width:Math.max(1,Math.round(innerWidth)),height:Math.max(1,Math.round(innerHeight)),size:'stretch',minWidth:300,maxWidth:1000,minHeight:520,maxHeight:1600,autoSize:true,usePortrait:true,showCover:true,startPage:0,flippingTime:700,drawShadow:true,maxShadowOpacity:.32,mobileScrollSupport:false});pf.loadFromHTML(pages);
  const lockNavigation=()=>{navigationLocked=true;book.style.pointerEvents='none';document.querySelector('.tap-left').style.pointerEvents='none';document.querySelector('.tap-right').style.pointerEvents='none'};
  const unlockNavigation=()=>{navigationLocked=false;book.style.pointerEvents='';document.querySelector('.tap-left').style.pointerEvents='';document.querySelector('.tap-right').style.pointerEvents=''};

  const PI='31415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679',stream=[];let w=0,h=0,dpr=1,start=0,vacuum=0,vacuumStarted=0;
  const hash=n=>{const x=Math.sin(n*12.9898)*43758.5453;return x-Math.floor(x)},clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),smooth=x=>x*x*(3-2*x);
  for(let i=0;i<520;i++)stream.push({offset:hash(i+1),lane:hash(i+101),speed:.55+hash(i+201)*.9,size:.72+hash(i+301)*.72,alpha:.26+hash(i+401)*.48,digit:PI[i%PI.length],phase:hash(i+501)*Math.PI*2});
  function forewordProgress(){if(current===sealIndex)return 1;const k=forewordPages.findIndex(x=>x.i===current);if(k<0)return 0;return forewordPages.length<=1?0:k/(forewordPages.length-1)}
  function glyphState(){const p=forewordProgress(),migration=smooth(clamp((p-.08)/.92)),late=Math.pow(p,2.25);return{p,pop:.22+.78*Math.pow(p,.82),velocity:.10+.30*migration+1.45*late,direction:.04+.96*Math.pow(migration,1.7)}}
  function syncOverlay(){const visible=current>=1&&current<=sealIndex;if(!visible){canvas.style.display='none';return}canvas.style.display='block';const r=pages[current].getBoundingClientRect();if(!r.width||!r.height)return;canvas.style.left=r.left+'px';canvas.style.top=r.top+'px';canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';w=r.width;h=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.max(1,Math.round(w*dpr));canvas.height=Math.max(1,Math.round(h*dpr));ctx.setTransform(dpr,0,0,dpr,0,0)}
  function beginVacuum(){if(vacuumStarted)return;vacuumStarted=performance.now();vacuum=.001}
  function setPage(i){current=Math.max(0,Math.min(last,Number(i)||0));if(current!==sealIndex){vacuum=0;vacuumStarted=0}else beginVacuum();status.textContent=`${current+1} / ${pages.length}`;requestAnimationFrame(syncOverlay);dispatchEvent(new CustomEvent('house:page',{detail:{current,pages,forewordProgress:forewordProgress()}}))}
  pf.on('flip',e=>setPage(e.data));
  const next=()=>{if(navigationLocked)return;if(current<last){if(current===sealIndex-1)beginVacuum();pf.flipNext()}},prev=()=>{if(navigationLocked)return;if(current>0)pf.flipPrev()};
  const interactiveAt=(x,y)=>{const el=document.elementFromPoint(x,y),control=el?.closest('button,a,input,select,textarea,[role="button"],[data-house-interactive]');return !!control&&!control.classList.contains('tap-left')&&!control.classList.contains('tap-right')};
  document.querySelector('.tap-right').addEventListener('pointerup',e=>{e.preventDefault();if(navigationLocked||interactiveAt(e.clientX,e.clientY))return;next()});document.querySelector('.tap-left').addEventListener('pointerup',e=>{e.preventDefault();if(navigationLocked||interactiveAt(e.clientX,e.clientY))return;prev()});addEventListener('keydown',e=>{if(navigationLocked)return;if(e.key==='ArrowRight')next();if(e.key==='ArrowLeft')prev()});
  function draw(ts){if(!start)start=ts;const t=(ts-start)/1000;if(vacuumStarted)vacuum=clamp((performance.now()-vacuumStarted)/1350);if(canvas.style.display!=='none'&&w&&h){ctx.clearRect(0,0,w,h);const s=glyphState(),count=Math.floor(stream.length*s.pop),direction=s.direction,exitX=w*1.12,exitY=h*.5;ctx.textAlign='center';ctx.textBaseline='middle';ctx.globalCompositeOperation='source-over';ctx.shadowBlur=0;
    for(let i=0;i<count;i++){const g=stream[i],baseX=hash(i+701)*w,baseY=hash(i+801)*h,driftX=Math.sin(t*.24+g.phase)*w*.018,driftY=Math.cos(t*.19+g.phase*1.3)*h*.014,flow=t*18*g.speed*s.velocity;let x=(baseX+driftX+flow*direction)%(w*1.12)-w*.06,y=baseY+driftY+Math.sin(t*.6+i)*h*.006*direction,alpha=g.alpha*(.62+.38*s.pop);
      if(vacuum>0){const q=Math.pow(vacuum,1.7),stagger=clamp((vacuum-hash(i+901)*.28)/.72),pull=Math.pow(stagger,2.2);x=x+(exitX-x)*pull;y=y+(exitY-y)*pull;alpha*=1-Math.pow(stagger,3.2);if(q>.88&&stagger>.7)alpha*=.35}
      if(alpha<.018)continue;ctx.font=`${Math.max(6,w*.0102*g.size)}px ui-monospace,SFMono-Regular,Menlo,monospace`;ctx.fillStyle=`rgba(23,21,19,${clamp(alpha,0,.76)})`;ctx.fillText(g.digit,x,y)}
  }requestAnimationFrame(draw)}
  requestAnimationFrame(syncOverlay);setTimeout(syncOverlay,120);setTimeout(syncOverlay,450);addEventListener('resize',()=>requestAnimationFrame(syncOverlay),{passive:true});requestAnimationFrame(draw);
  window.HouseBook={book,pages,pf,getCurrent:()=>current,getForewordProgress:forewordProgress,getGlyphState:glyphState,lockNavigation,unlockNavigation,isNavigationLocked:()=>navigationLocked};dispatchEvent(new CustomEvent('house:ready',{detail:window.HouseBook}));
})();

(()=>{const history=[],MAX_HISTORY=5,MIN_DWELL=1200,MAX_DWELL=120000;let enteredAt=null,currentPage=null,estimatedReadingDurationMs=12000;const median=v=>{v=[...v].sort((a,b)=>a-b);return v.length?v[Math.floor(v.length/2)]:estimatedReadingDurationMs};const enter=page=>{currentPage=Number(page);enteredAt=performance.now();dispatchEvent(new CustomEvent('house:reading-enter',{detail:{page:currentPage}}))};const leave=page=>{if(enteredAt===null)return null;const duration=performance.now()-enteredAt;enteredAt=null;const p=Number(page),valid=duration>=MIN_DWELL&&duration<=MAX_DWELL&&p===currentPage;if(valid){history.push(duration);if(history.length>MAX_HISTORY)history.shift();estimatedReadingDurationMs=median(history)}const detail={page:p,durationMs:duration,accepted:valid,history:[...history],estimatedReadingDurationMs};dispatchEvent(new CustomEvent('house:reading-leave',{detail}));return detail};window.HouseReadingClock={enter,leave,getEstimate:()=>estimatedReadingDurationMs,getHistory:()=>[...history],reset:()=>{history.length=0;enteredAt=null;currentPage=null;estimatedReadingDurationMs=12000}};addEventListener('house:page',e=>{const page=e.detail?.current;if(page!==currentPage){if(enteredAt!==null)leave(currentPage);enter(page)}});addEventListener('house:ready',e=>{if(e.detail?.getCurrent)enter(e.detail.getCurrent())})})();