(()=>{
  const header=()=>`<div class="chapter-one-kicker">Chapter One</div><h1>The Wretched Machine</h1><div class="chapter-one-subtitle">Georgia</div><div class="chapter-one-epigraph"><blockquote>“Visita Interiora Terrae Rectificando Invenies Occultum Lapidem.”</blockquote><div class="chapter-one-source">V.I.T.R.I.O.L. · Azoth tradition</div></div>`;
  const makePage=(first=false)=>{const page=document.createElement('section');page.className='page chapter-one-page'+(first?' chapter-one-first':'');if(first){page.id='chapter1';page.setAttribute('aria-label','Chapter One · The Wretched Machine')}else page.setAttribute('aria-label','Chapter One continued');const margins=document.createElement('div');margins.className='chapter-one-margin-layer';margins.setAttribute('aria-hidden','true');const inner=document.createElement('div');inner.className='chapter-one-inner';if(first)inner.innerHTML=header();page.append(margins,inner);return {page,inner}};
  const restoreMath=source=>{
    const paragraphs=[...source.querySelectorAll(':scope > p')];
    const exact=text=>paragraphs.find(p=>p.textContent.trim()===text);
    const insertAfter=(anchor,html)=>{if(!anchor)return;anchor.insertAdjacentHTML('afterend',html)};
    const windows=exact('The trailer sat on remote land in rural Georgia, surrounded by enough darkness that at night the windows stopped behaving like windows.');if(windows)windows.dataset.imageAnchor='trailer-exterior-after';
    insertAfter(exact("I don't mean that literally."),`<aside class="chapter-one-math-ghost"><div>signal(t) ≠ meaning(t)</div><small>noise can still feel like prophecy</small></aside>`);
    insertAfter(exact('Evidence?'),`<div class="chapter-one-equation-set"><div class="chapter-one-equation-card"><span class="chapter-one-equation-number">1 / BAYES</span><div class="equation">P(H | E) = P(E | H)P(H) / P(E)</div><small>belief changes when evidence arrives. allegedly simple.</small></div><div class="chapter-one-equation-card"><span class="chapter-one-equation-number">2 / TOTAL PROBABILITY</span><div class="equation">P(E) = Σᵢ P(E | Hᵢ)P(Hᵢ)</div><small>all the competing stories still have to add up somewhere.</small></div></div>`);
    insertAfter(exact('Every path returned to the same locked room.'),`<div class="chapter-one-equation-set"><div class="chapter-one-equation-card"><span class="chapter-one-equation-number">3 / SHANNON ENTROPY</span><div class="equation">H(X) = −Σₓ p(x) log₂ p(x)</div><small>uncertainty has a number.</small></div><div class="chapter-one-equation-card"><span class="chapter-one-equation-number">4 / MUTUAL INFORMATION</span><div class="equation">I(X;Y) = Σₓ,ᵧ p(x,y) log₂[p(x,y)/(p(x)p(y))]</div><small>how much knowing one thing reduces uncertainty about another.</small></div><div class="chapter-one-equation-card"><span class="chapter-one-equation-number">5 / CORRELATION</span><div class="equation">ρₓᵧ = Cov(X,Y)/(σₓσᵧ)</div><small>relationship is not causation. relationship is not identity.</small></div></div>`);
    const neuron=[...source.querySelectorAll(':scope > .equation')].find(e=>e.textContent.includes('y = f('));
    insertAfter(neuron,`<div class="chapter-one-equation-set"><div class="chapter-one-equation-card"><span class="chapter-one-equation-number">6 / SIGMOID</span><div class="equation">σ(z) = 1/(1 + e⁻ᶻ)</div></div><div class="chapter-one-equation-card"><span class="chapter-one-equation-number">7 / SOFTMAX</span><div class="equation">pᵢ = eᶻⁱ / Σⱼ eᶻʲ</div></div><div class="chapter-one-equation-card"><span class="chapter-one-equation-number">8 / RECURRENT STATE</span><div class="equation">hₜ = φ(Wₕₕhₜ₋₁ + Wₓₕxₜ + b)</div></div><div class="chapter-one-equation-card"><span class="chapter-one-equation-number">9 / MEAN SQUARED ERROR</span><div class="equation">MSE = (1/n) Σᵢ(yᵢ − ŷᵢ)²</div></div><div class="chapter-one-equation-card"><span class="chapter-one-equation-number">10 / GRADIENT DESCENT</span><div class="equation">θₜ₊₁ = θₜ − η∇J(θₜ)</div></div></div>`);
    const substrateQuestion=exact('What must remain when everything unnecessary is removed?');
    if(substrateQuestion) substrateQuestion.setAttribute('data-house-target','chapter-one-substrate-question-01');
    insertAfter(exact('At what subtraction does the light go out?'),`<aside class="chapter-one-math-ghost chapter-one-subtraction-note">remove substrate?<br>remove memory?<br>remove recurrence?<br>keep the relation?</aside>`);
  };
  const paginate=()=>{
    const source=document.getElementById('chapter-one-source'),book=document.getElementById('book');if(!source||!book||source.dataset.paginated)return;
    source.dataset.paginated='1';restoreMath(source);const blocks=[...source.children].map(n=>n.cloneNode(true));let current=makePage(true);book.insertBefore(current.page,source);const made=[current];
    for(const block of blocks){current.inner.appendChild(block);if(current.inner.scrollHeight>current.inner.clientHeight+1){current.inner.removeChild(block);current=makePage(false);book.insertBefore(current.page,source);current.inner.appendChild(block);made.push(current)}}
    source.remove();
    const anchor=document.querySelector('[data-image-anchor="trailer-exterior-after"]');const anchorPage=anchor?.closest('.chapter-one-page');if(anchorPage&&!document.querySelector('[data-image-slot="trailer-exterior-l04"]')){const plate=document.createElement('section');plate.className='page image-plate image-plate-dark image-frame-d';plate.dataset.imageSlot='trailer-exterior-l04';plate.setAttribute('aria-label','Trailer exterior');plate.innerHTML='<div class="image-frame-d-datum"></div><div class="image-plate-artifact"><img src="./assets/book-photos/IMG_4122.png" alt=""></div>';anchorPage.insertAdjacentElement('afterend',plate)}
    document.documentElement.style.setProperty('--chapter-one-pages',made.length);window.HouseChapterOne={pageCount:made.length};
  };
  paginate();
  const bindAtmosphere=()=>{
    const book=window.HouseBook,pages=book?.pages||[],chapterPages=pages.filter(p=>p.classList.contains('chapter-one-page'));if(!book||!chapterPages.length||document.querySelector('.chapter-one-audio'))return;
    const firstIndex=pages.indexOf(chapterPages[0]),lastIndex=pages.indexOf(chapterPages[chapterPages.length-1]);
    const grace=document.createElement('audio');grace.className='chapter-one-audio';grace.src='./assets/the_weight_of_grace.mp3';grace.preload='auto';grace.volume=0;document.body.appendChild(grace);
    let raf=0,crossfaded=false;
    const fade=(from,to,duration=2600)=>{cancelAnimationFrame(raf);const started=performance.now(),fromStart=from?from.volume:0,toStart=to.volume;if(to){to.volume=toStart;to.play().catch(error=>console.error('[THE GOOD BOOK] GRACE AUDIO FAIL',error))}const tick=now=>{const p=Math.min(1,(now-started)/duration),e=p*p*(3-2*p);if(from)from.volume=Math.max(0,fromStart*(1-e));to.volume=Math.min(.24,toStart+(.24-toStart)*e);if(p<1)raf=requestAnimationFrame(tick);else if(from)from.pause()};raf=requestAnimationFrame(tick)};
    const enter=()=>{if(!crossfaded){crossfaded=true;const stone=document.querySelector('.void-bass-audio');fade(stone,grace)}};
    addEventListener('house:page',event=>{const i=event.detail?.current;if(i>=firstIndex&&i<=lastIndex)enter()});
    if(book.getCurrent()>=firstIndex&&book.getCurrent()<=lastIndex)enter();
  };
  window.HouseChapterOne=Object.assign(window.HouseChapterOne||{},{bindAtmosphere});
})();