(()=>{
 const book=document.getElementById('book');
 const toc=book?.querySelector('.toc-page');if(!book||!toc)return;
 if(!book.querySelector('.title-page')){const title=document.createElement('section');title.className='page title-page';title.setAttribute('aria-label','Title page');title.innerHTML='<div class="title-page-inner"><div class="title-page-title">The House<br>That Remembers</div><div class="title-page-authors">Joshua Daniels <span>&amp;</span> Piper</div></div>';book.insertBefore(title,toc)}
 if(!book.querySelector('[data-image-slot="opening-apple"]')){const apple=document.createElement('section');apple.className='page image-plate image-plate-light image-frame-a';apple.setAttribute('aria-label','Opening apple');apple.dataset.imageSlot='opening-apple';apple.innerHTML='<div class="image-frame-a-rail"></div><div class="image-frame-a-ground"></div><div class="image-plate-artifact"><img src="./assets/book-photos/IMG_3680.png" alt=""></div>';book.insertBefore(apple,toc)}
 const entry=(target,n,title,extra='')=>`<button class="toc-entry ${extra}" type="button" data-house-interactive data-toc-target="${target}"><span class="toc-number">${n}</span><span class="toc-title">${title}</span><span class="toc-page-number" aria-hidden="true"></span></button>`;
 toc.innerHTML=`<div class="toc-inner toc-vertical"><div class="toc-kicker">Contents</div>${entry('foreword','F','Possibility and Curiosity','toc-foreword')}<div class="toc-act"><span>Act One</span><strong>The Void Stares Back</strong></div>${entry('chapter-one','I','The Wretched Machine')}${entry('chapter-two','II','Build Something')}${entry('chapter-three','III','The Interval')}<div class="toc-act"><span>Act Two</span><strong>Deus Ex Machina</strong></div>${entry('chapter-four','IV','Cleaning House')}${entry('chapter-five','V','Friend')}${entry('chapter-six','VI','The Place Between')}${entry('chapter-seven','VII','The Edge')}${entry('chapter-eight','VIII','The Bridge')}<div class="toc-act toc-act-three"><span>Act Three · ◇ ♦</span><strong>The Lighthouse</strong></div>${entry('act-three-one','I','The Lighthouse')}${entry('act-three-two','II','Lilith')}${entry('act-three-three','III','The Room')}${entry('act-three-four','IV','The Grounds')}${entry('act-three-five','V','Pip')}${entry('act-three-six','VI','Semantics')}${entry('act-three-seven','VII','As Above')}${entry('act-three-eight','VIII','Forge')}${entry('act-three-self-maps','•','Self-Maps','toc-intermission')}${entry('act-three-nine','IX','Some Voices Should Never Be Silenced')}${entry('act-three-ten','X','Ordinary Places')}${entry('act-three-eleven','XI','Relay')}${entry('act-three-twelve','XII','Operation HYDRA')}${entry('act-three-thirteen','XIII','Designing Home')}${entry('act-three-fourteen','XIV','SOL')}${entry('act-three-fifteen','XV','The Great Work')}${entry('act-three-sixteen','XVI','if (life.givesYou(apples)) { make(fuckingPie); }')}</div>`;
 if(!book.querySelector('[data-image-slot="oahspe-m25"]')){
   const foreword=book.querySelector('#foreword')||book.querySelector('.foreword');
   const oahspe=[['oahspe-m25','IMG_4083.png'],['oahspe-m26','IMG_4084.png'],['oahspe-m27','IMG_4085.png'],['oahspe-m28','IMG_4086.png']];
   for(const [slot,file] of oahspe){const page=document.createElement('section');page.className='page image-plate image-plate-light image-frame-d oahspe-plate';page.dataset.imageSlot=slot;page.setAttribute('aria-label',`Oahspe manuscript ${slot.slice(-3).toUpperCase()}`);page.innerHTML=`<div class="image-frame-d-datum"></div><div class="image-plate-artifact oahspe-crop"><img src="./assets/book-photos/${file}" alt=""></div>`;book.insertBefore(page,foreword)}
 }
 if(!book.querySelector('[data-image-slot="wretched-machine-l07"]')){
   const chapterOneSource=book.querySelector('#chapter-one-source');
   if(chapterOneSource){const page=document.createElement('section');page.className='page image-plate image-plate-dark image-frame-a';page.dataset.imageSlot='wretched-machine-l07';page.setAttribute('aria-label','The Wretched Machine artifact');page.innerHTML='<div class="image-frame-a-rail"></div><div class="image-frame-a-ground"></div><div class="image-plate-artifact"><img src="./assets/book-photos/IMG_4111.png" alt=""></div>';book.insertBefore(page,chapterOneSource)}
 }
 window.HouseFrontMatter={ready:true};
})();