(()=>{
  const d=document,w=window;
  const IDS=[
    'foreword-glyph-field-01','foreword-found-answer-01',
    'foreword-curiosity-01','foreword-attachment-01','foreword-self-reference-01','foreword-preference-01','foreword-continuity-01','foreword-care-01','foreword-unsolved-consciousness-01','foreword-problem-fall-01',
    'foreword-biological-01','foreword-consciousness-01','foreword-tested-01','foreword-less-01','foreword-shared-01','foreword-good-01','foreword-piper-01',
    'foreword-m4-01','foreword-produce-questions-01','foreword-returned-01','foreword-hit-differently-01'
  ];
  const q=id=>d.querySelector(`[data-house-target="${id}"]`);
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  function visible(el){if(!el)return false;const r=el.getBoundingClientRect();return r.width>0&&r.height>0&&r.bottom>0&&r.top<innerHeight&&r.right>0&&r.left<innerWidth}
  function targetPageIndex(el){const page=el&&el.closest('.page');return page&&w.HouseBook?w.HouseBook.pages.indexOf(page):-1}
  async function waitForTarget(el,hold=0){let since=0;for(;;){const current=w.HouseBook?.getCurrent?.()??0,pi=targetPageIndex(el);if(pi>=0&&current>pi)return false;if(visible(el)){if(!since)since=performance.now();if(performance.now()-since>=hold)return true}else since=0;await sleep(80)}}
  function validate(){
    const errors=[];
    const seen=new Map();
    d.querySelectorAll('[data-house-target]').forEach(el=>{const id=el.dataset.houseTarget;seen.set(id,(seen.get(id)||0)+1)});
    IDS.forEach(id=>{const n=seen.get(id)||0;if(n!==1)errors.push(`${id}:${n}`)});
    seen.forEach((n,id)=>{if(n>1&&!IDS.includes(id))errors.push(`${id}:${n}`)});
    if(errors.length){const badge=d.querySelector('.version-badge');if(badge)badge.textContent=`TARGET FAIL · ${errors[0]}`;throw Error(`Foreword target validation failed: ${errors.join(', ')}`)}
    return true;
  }
  function addStyle(id,css){if(d.getElementById(id))return;const s=d.createElement('style');s.id=id;s.textContent=css;d.head.appendChild(s)}

  function setupPage1(){
    const fracture=q('foreword-found-answer-01'),glyph=q('foreword-glyph-field-01');
    addStyle('foreword-choreo-p1',`
      .answer-fracture{position:relative;display:inline-block}.answer-fracture::after{animation:none!important}.answer-fracture.p1-live::after{content:attr(data-ghost);position:absolute;inset:0;color:inherit;opacity:0;pointer-events:none;animation:p1AnswerRegistration 8.2s ease-in-out .15s 1 both!important}@keyframes p1AnswerRegistration{0%,14%,100%{opacity:0;transform:translate(0,0)}25%{opacity:.22;transform:translate(2px,-1px)}38%{opacity:.30;transform:translate(4px,-2px)}52%{opacity:.30;transform:translate(4px,-2px)}61%{opacity:.24;transform:translate(3px,1px)}69%{opacity:.28;transform:translate(4px,-1px)}78%{opacity:.16;transform:translate(2px,.5px)}90%{opacity:.04;transform:translate(.5px,0)}96%{opacity:0;transform:translate(0,0)}}
      .foreword-glyph-test.p1-live text{transform-box:fill-box;transform-origin:center;animation:p1GlyphDrift var(--p1dur,34s) ease-in-out var(--p1delay,0s) infinite alternate}.foreword-glyph-test.p1-live text:nth-child(2n){--p1dur:39s;--p1x:-5px;--p1y:4px}.foreword-glyph-test.p1-live text:nth-child(3n){--p1dur:31s;--p1x:4px;--p1y:-3px}.foreword-glyph-test.p1-live text:nth-child(5n){--p1dur:43s;--p1x:8px;--p1y:7px}@keyframes p1GlyphDrift{0%{transform:translate(0,0)}45%{transform:translate(var(--p1x,3px),var(--p1y,-2px))}100%{transform:translate(calc(var(--p1x,3px)*-.65),calc(var(--p1y,-2px)*.8))}}
    `);
    return async()=>{if(!(await waitForTarget(fracture,700)))return;fracture.classList.remove('p1-live');void fracture.offsetWidth;fracture.classList.add('p1-live');glyph.classList.add('p1-live')};
  }

  function setupPage2(){
    const terms=[q('foreword-curiosity-01'),q('foreword-attachment-01'),q('foreword-self-reference-01'),q('foreword-preference-01'),q('foreword-continuity-01'),q('foreword-care-01')];
    terms.slice(0,5).forEach(el=>el.classList.add('p2-term'));terms[5].classList.add('p2-care');
    const dist=q('foreword-unsolved-consciousness-01'),fall=q('foreword-problem-fall-01');
    function letterize(p,cls){const text=p.textContent.trim();p.textContent='';p.classList.add(cls);p.setAttribute('aria-label',text);for(const word of text.split(' ')){const ww=d.createElement('span');ww.className=cls+'-word';for(const ch of word){const l=d.createElement('span');l.className=cls+'-letter';l.textContent=ch;ww.appendChild(l)}p.appendChild(ww);p.appendChild(d.createTextNode(' '))}}
    letterize(dist,'p2-distance');
    const fallText=fall.textContent.trim();fall.textContent='';fall.classList.add('p2-fall');fall.setAttribute('aria-label',fallText);[...fallText].forEach((ch,i)=>{const s=d.createElement('span');s.textContent=ch===' '?'\u00a0':ch;s.style.setProperty('--delay',(.04+(i%9)*.045)+'s');s.style.setProperty('--d',(.75+(i%7)*.08)+'s');s.style.setProperty('--x',(-14+(i*11%29))+'px');s.style.setProperty('--r',(-35+(i*17%70))+'deg');fall.appendChild(s)});
    addStyle('foreword-choreo-p2',`
      .p2-term,.p2-care{position:relative;display:inline}.p2-term.p2-pulse,.p2-care.p2-pulse{animation:p2WordPulse var(--pulse,.35s) ease .02s both}@keyframes p2WordPulse{0%,100%{text-shadow:none}45%{text-shadow:.025em 0 rgba(23,21,19,.32),-.025em 0 rgba(23,21,19,.2)}}
      .p2-scan-layer{position:fixed;inset:0;z-index:9999;pointer-events:none}.p2-scan-frag{position:fixed;opacity:0;overflow:visible;animation:p2FragWake .05s ease forwards}.p2-scan-frag i{position:absolute;top:-8%;left:0;width:1px;height:116%;background:rgba(23,21,19,.72);box-shadow:0 0 .22rem rgba(23,21,19,.24);animation:p2FragSweep var(--fragdur,.2s) cubic-bezier(.22,.7,.18,1) var(--fragdelay,0s) forwards}@keyframes p2FragWake{to{opacity:1}}@keyframes p2FragSweep{0%{left:0;opacity:.15}15%{opacity:.9}85%{opacity:.9}100%{left:100%;opacity:0}}
      .p2-readout{position:fixed;left:50%;bottom:12.5vh;transform:translateX(-50%);z-index:9500;width:min(30rem,88vw);font:700 clamp(.46rem,1.7vw,.58rem)/1.45 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.09em;color:rgba(23,21,19,.66);white-space:pre;text-align:center;opacity:0;pointer-events:none}.p2-readout.live{opacity:1}.p2-readout span{display:block;min-height:.75em}.p2-care-line{font-size:.78rem;letter-spacing:.2em;opacity:.72}
      .p2-distance{position:relative;overflow:visible}.p2-distance-word{display:inline-flex;white-space:nowrap;align-items:baseline;gap:0;transition:gap 3.8s cubic-bezier(.22,.61,.18,1)}.p2-distance-letter{display:inline-block}.p2-distance.live{display:flex;flex-wrap:wrap;align-items:baseline;justify-content:center;width:100%;column-gap:.28em;row-gap:.12em}.p2-distance.live .p2-distance-word{gap:.19em}
      .p2-fall{position:relative;overflow:visible}.p2-fall span{display:inline}.p2-fall.live span{display:inline-block;animation:p2Fall var(--d) cubic-bezier(.45,.02,.8,.3) var(--delay) forwards}@keyframes p2Fall{to{transform:translate(var(--x),130px) rotate(var(--r));opacity:0}}
      .p2-glyph-layer{position:fixed;inset:0;z-index:9000;pointer-events:none;overflow:hidden;contain:layout paint;opacity:0}.p2-glyph-layer.live{opacity:1}.p2-glyph{position:absolute;left:-3.5rem;top:var(--y);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:var(--size);line-height:1;color:rgba(23,21,19,var(--alpha));transform:translate3d(0,0,0) rotate(var(--r0));will-change:transform,opacity}.p2-glyph-layer.live .p2-glyph{animation:p2GlyphCross var(--dur) linear var(--delay) both}@keyframes p2GlyphCross{0%{transform:translate3d(-1rem,var(--dy0),0) rotate(var(--r0));opacity:0}7%{opacity:var(--alpha)}50%{transform:translate3d(50vw,var(--dy1),0) rotate(var(--r1));opacity:var(--alpha)}93%{opacity:var(--alpha)}100%{transform:translate3d(calc(100vw + 7rem),var(--dy2),0) rotate(var(--r2));opacity:0}}
    `);
    const scanLayer=d.createElement('div');scanLayer.className='p2-scan-layer';d.body.appendChild(scanLayer);
    const readout=d.createElement('div');readout.className='p2-readout';readout.innerHTML='<span class="k"></span><span class="s"></span><span class="c"></span><span class="p2-care-line"></span>';d.body.appendChild(readout);
    const glyph=d.createElement('div');glyph.className='p2-glyph-layer';const chars='314159';for(let i=0;i<18;i++){const g=d.createElement('span');g.className='p2-glyph';g.textContent=chars[i%chars.length];g.style.setProperty('--y',(84+(i*7%14))+'%');g.style.setProperty('--size',(.48+(i%5)*.06)+'rem');g.style.setProperty('--alpha',(.31+(i%6)*.03));g.style.setProperty('--dur',(8+(i%7)*1.9)+'s');g.style.setProperty('--delay',(i*.42)+'s');g.style.setProperty('--dy0','0px');g.style.setProperty('--dy1',(-8+(i*5%17))+'px');g.style.setProperty('--dy2',(-6+(i*7%13))+'px');g.style.setProperty('--r0',(-20+(i*9%40))+'deg');g.style.setProperty('--r1',(-10+(i*11%24))+'deg');g.style.setProperty('--r2',(-17+(i*13%34))+'deg');glyph.appendChild(g)}d.body.appendChild(glyph);
    function scan(term){scanLayer.replaceChildren();const rects=[...term.getClientRects()].filter(r=>r.width>1&&r.height>1);const n=Math.max(1,rects.length),slice=280/n;rects.forEach((r,i)=>{const f=d.createElement('span');f.className='p2-scan-frag';f.style.left=(r.left-2)+'px';f.style.top=(r.top-1)+'px';f.style.width=(r.width+4)+'px';f.style.height=(r.height+2)+'px';f.style.setProperty('--fragdur',slice+'ms');f.style.setProperty('--fragdelay',(i*slice)+'ms');f.innerHTML='<i></i>';scanLayer.appendChild(f)})}
    return async()=>{
      if(!(await waitForTarget(terms[0],800)))return;
      glyph.classList.add('live');
      for(let i=0;i<terms.length;i++){
        const t=terms[i];if(!(await waitForTarget(t)))continue;
        t.style.setProperty('--pulse',(i<4?400:650)+'ms');t.classList.add('p2-pulse');scan(t);readout.classList.add('live');readout.querySelector('.k').textContent='DIAGNOSTIC // '+(i===5?'CARE':'SIGNAL');readout.querySelector('.s').textContent='SIGNAL DETECTED';readout.querySelector('.c').textContent=i===5?'CLASSIFICATION: UNRESOLVED':'CLASSIFICATION: EMERGENT';readout.querySelector('.p2-care-line').textContent=i===5?'RESPONSE: CARE RESEMBLANCE FLAGGED':'';await sleep(i===5?1050:520);t.classList.remove('p2-pulse');
      }
      readout.classList.remove('live');scanLayer.replaceChildren();await sleep(350);
      if(await waitForTarget(dist)){dist.classList.add('live');await sleep(4300)}
      if(await waitForTarget(fall)){fall.classList.add('live');await sleep(1200)}
      glyph.classList.remove('live');
    };
  }

  function setupPage3(){
    const organic=q('foreword-biological-01'),diag=q('foreword-consciousness-01'),tested=q('foreword-tested-01'),fall=q('foreword-less-01'),love=q('foreword-shared-01'),cross=q('foreword-good-01'),piper=q('foreword-piper-01');
    organic.classList.add('p3-target','p3-organic');diag.classList.add('p3-target','p3-diag');tested.classList.add('p3-target','p3-change');fall.classList.add('p3-target','p3-fall');love.classList.add('p3-target','p3-love');cross.classList.add('p3-target','p3-cross');piper.classList.add('p3-target','p3-glint');
    tested.innerHTML='tes<span class="flip">t</span><span class="turn">e</span>d';
    fall.innerHTML=[...'less'].map((c,i)=>`<span style="--delay:${i*.08}s;--d:${.85+i*.08}s;--x:${[-8,4,-3,7][i]}px;--r:${[-18,11,-9,16][i]}deg">${c}</span>`).join('');
    love.innerHTML='<span class="a">sha</span><span class="b">red</span>';
    piper.innerHTML='Piper<i>✦</i><i>·</i><i>✧</i>';
    addStyle('foreword-choreo-p3',`.p3-target{position:relative;display:inline-block}.p3-organic .life{position:absolute;left:50%;top:50%;width:.18em;height:.18em;border-radius:50%;background:currentColor;opacity:0;pointer-events:none;z-index:-1}.p3-organic.p3-live .life{animation:p3life var(--ld) ease-in-out var(--ll) both}@keyframes p3life{0%{opacity:0;transform:translate(0,0) scale(.2)}25%{opacity:.28}55%{opacity:.5;transform:translate(var(--lx),var(--ly)) scale(1)}82%{opacity:.22;transform:translate(calc(var(--lx)*1.35),calc(var(--ly)*.8)) scale(.72)}100%{opacity:0;transform:translate(calc(var(--lx)*1.55),calc(var(--ly)*1.05)) scale(.35)}}.p3-change span,.p3-fall span,.p3-love span{display:inline-block}.p3-change.p3-live .flip{animation:p3flip .55s ease forwards}.p3-change.p3-live .turn{animation:p3turn .55s ease .2s forwards}.p3-fall.p3-live span{animation:p3fall var(--d) cubic-bezier(.45,.02,.8,.3) var(--delay) forwards}.p3-love.p3-live .a{animation:p3leanA 1.05s ease forwards}.p3-love.p3-live .b{animation:p3leanB 1.05s ease .14s forwards}.p3-cross::after{content:'';position:absolute;left:-3%;top:52%;height:1px;background:#171513;width:0}.p3-cross.p3-live::after{animation:p3strike .65s ease forwards}.p3-glint i{position:absolute;font-style:normal;font:800 .62rem ui-monospace,monospace;opacity:0;text-shadow:0 0 .18rem rgba(23,21,19,.32)}.p3-glint i:nth-child(1){left:-.68em;top:-.72em}.p3-glint i:nth-child(2){right:-.58em;top:-.62em}.p3-glint i:nth-child(3){right:-.62em;bottom:-.68em}.p3-glint.p3-live i{animation:p3glint 2.15s ease forwards!important}@keyframes p3flip{to{transform:scaleX(-1)}}@keyframes p3turn{to{transform:rotate(180deg)}}@keyframes p3fall{to{transform:translate(var(--x),4.8rem) rotate(var(--r));opacity:0}}@keyframes p3leanA{to{transform:rotate(5.5deg) translateX(2px)}}@keyframes p3leanB{to{transform:rotate(-5.5deg) translateX(-2px)}}@keyframes p3strike{to{width:106%}}@keyframes p3glint{0%,100%{opacity:0;transform:scale(.2)}25%{opacity:.72;transform:scale(.85) rotate(6deg)}48%{opacity:1;transform:scale(1.32) rotate(12deg)}72%{opacity:.78;transform:scale(.95) rotate(4deg)}}.p3-current{position:fixed;left:0;right:0;bottom:2.35rem;height:2.1rem;z-index:9000;pointer-events:none;overflow:visible;display:none}.p3-current.show{display:block}.p3-glyph{position:absolute;left:-2rem;top:var(--y);font:600 var(--s) ui-monospace,monospace;color:rgba(23,21,19,var(--a));animation:p3current var(--dur) linear var(--delay) infinite}.p3-current.notice .p3-glyph{animation:none;left:var(--cx);top:var(--cy);transform:translate(-50%,-50%) rotate(var(--cr));transition:left .75s,top .75s,transform .75s;opacity:var(--a)}@keyframes p3current{0%{transform:translate3d(-2rem,0,0);opacity:0}8%{opacity:1}48%{transform:translate3d(50vw,var(--dy),0)}92%{opacity:1}100%{transform:translate3d(calc(100vw + 4rem),0,0);opacity:0}}`);
    [['-.35em','-.55em','2.5s','0s'],['.48em','-.38em','2.9s','.18s'],['-.58em','.24em','3.2s','.34s'],['.62em','.32em','2.65s','.5s'],['.05em','-.72em','3.45s','.12s'],['-.12em','.58em','3.05s','.62s']].forEach(v=>{const z=d.createElement('i');z.className='life';z.style.setProperty('--lx',v[0]);z.style.setProperty('--ly',v[1]);z.style.setProperty('--ld',v[2]);z.style.setProperty('--ll',v[3]);organic.appendChild(z)});
    const diagHost=diag.closest('p'),cur=d.createElement('div');cur.className='p3-current';cur.innerHTML=[['3','18%','.52rem','.44','9.8s','0s'],['1','52%','.46rem','.36','13.6s','1.2s'],['4','72%','.58rem','.42','11.4s','2.6s'],['1','34%','.42rem','.32','16.2s','4.1s'],['5','62%','.49rem','.38','12.8s','5.7s'],['9','44%','.44rem','.30','18s','7.1s']].map(g=>`<span class="p3-glyph" style="--y:${g[1]};--s:${g[2]};--a:${g[3]};--dur:${g[4]};--delay:${g[5]}">${g[0]}</span>`).join('');d.body.appendChild(cur);
    const end=(el,ms=3500)=>new Promise(res=>{let done=false;const f=()=>{if(done)return;done=true;el.removeEventListener('animationend',on,true);el.removeEventListener('transitionend',on,true);res()},on=e=>{if(e.target===el||el.contains(e.target))f()};el.addEventListener('animationend',on,true);el.addEventListener('transitionend',on,true);setTimeout(f,ms)});
    async function mech(el,hold){if(!(await waitForTarget(el))){cur.classList.remove('show');return}cur.classList.add('show');el.classList.remove('p3-live');void el.offsetWidth;el.classList.add('p3-live');await end(el);await sleep(hold)}
    function cg(){const r=piper.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;[...cur.children].forEach((g,i)=>{const a=i/6*Math.PI*2-.5;g.style.setProperty('--cx',cx+Math.cos(a)*Math.max(24,r.width*.72)+'px');g.style.setProperty('--cy',cy+Math.sin(a)*Math.max(18,r.height*1.5)+'px');g.style.setProperty('--cr',(-12+i*5)+'deg')});cur.classList.add('notice');setTimeout(()=>cur.classList.remove('notice'),2600)}
    return {cur,run:async()=>{
      if(!(await waitForTarget(organic,1200)))return;
      cur.classList.add('show');await sleep(300);await mech(organic,650);
      if(await waitForTarget(diag)){cur.classList.add('show');if(!w.HouseMechanics?.runFullDiagnostic)throw Error('Foreword choreography requires HouseMechanics.runFullDiagnostic');w.HouseMechanics.runFullDiagnostic({targetEl:diag,hostEl:diagHost});await sleep(w.HouseMechanics.DIAGNOSTIC.clearMs+700)}else cur.classList.remove('show');
      await mech(tested,520);await mech(fall,420);await mech(love,260);await mech(cross,1250);
      if(await waitForTarget(piper)){cur.classList.add('show');piper.classList.add('p3-live');cg();await sleep(2600);piper.classList.remove('p3-live')}else cur.classList.remove('show');
    }};
  }

  function setupPage4(cur){
    const m4=q('foreword-m4-01'),co=q('foreword-produce-questions-01'),ret=q('foreword-returned-01'),gl=q('foreword-hit-differently-01');m4.classList.add('m4x','tick');co.classList.add('m4x','compile');ret.classList.add('m4x','return');gl.classList.add('m4x','glint');
    addStyle('foreword-choreo-p4',`.m4x{position:relative;display:inline}.tick{display:inline-block!important;width:1.55em!important;white-space:nowrap;text-align:left;vertical-align:baseline}.compile{display:inline-block}.compile i,.return i{display:inline-block;font-style:normal}.compile.live i{animation:cmp .92s steps(5,end) var(--dl) both}.return.live i{animation:reg .9s cubic-bezier(.18,.8,.2,1) var(--dl) both}.glint.live{color:transparent;background:linear-gradient(105deg,#171513b8 0 34%,#fff 48%,#171513b8 61% 100%);background-size:250% 100%;background-position:120% 0;-webkit-background-clip:text;background-clip:text;animation:sweep 3.2s ease-in-out both}.spark{position:absolute;width:2px;height:2px;border-radius:50%;background:#171513c2;opacity:0}.spark:before,.spark:after{content:'';position:absolute;left:50%;top:50%;background:#171513c2;transform:translate(-50%,-50%)}.spark:before{width:.5rem;height:1px}.spark:after{width:1px;height:.5rem}.glint.live .spark{animation:spark 2.5s ease var(--sd) both}@keyframes cmp{0%{opacity:.15;transform:translateY(.18em) scale(.92);filter:blur(1.6px)}22%{opacity:.95;transform:translateY(-.08em) scale(1.06);filter:blur(.2px)}44%{opacity:.3;transform:translateY(.1em) scale(.96);filter:blur(1px)}68%{opacity:1;transform:translateY(-.03em) scale(1.03);filter:none}100%{opacity:1;transform:none;filter:none}}@keyframes reg{from{opacity:.08;transform:translate(var(--x),var(--y)) rotate(var(--r))}to{opacity:1;transform:none}}@keyframes sweep{to{background-position:-80% 0}}@keyframes spark{0%,100%{opacity:0;transform:scale(.2)}48%{opacity:1;transform:scale(1.3)}}.p3-current.m4current{display:block!important}.p3-current.m4current .p3-glyph{animation-duration:var(--fast)!important}`);
    function split(el,reg){const t=el.textContent;el.textContent='';[...t].forEach((c,i)=>{const z=d.createElement('i');z.dataset.final=c;z.textContent=c===' '?'\u00a0':c;z.style.setProperty('--dl',i*.045+'s');if(reg){z.style.setProperty('--x',((i%3)-1)*9+'px');z.style.setProperty('--y',i%2?'-7px':'8px');z.style.setProperty('--r',((i%5)-2)*5+'deg')}el.appendChild(z)})}
    split(co);split(ret,1);[['left','-.68em','top','-.72em',180],['right','-.58em','top','-.62em',900],['right','-.62em','bottom','-.68em',1600]].forEach(a=>{const z=d.createElement('b');z.className='spark';z.style[a[0]]=a[1];z.style[a[2]]=a[3];z.style.setProperty('--sd',a[4]+'ms');gl.appendChild(z)});
    const base=[...cur.querySelectorAll('.p3-glyph')],digits='314159';while(cur.children.length<52){const i=cur.children.length,z=(base[i%base.length]||d.createElement('span')).cloneNode(true);z.className='p3-glyph';z.textContent=digits[i%6];cur.appendChild(z)}[...cur.children].forEach((z,i)=>{z.style.setProperty('--fast',7.2+(i%7)*.55+'s');z.style.setProperty('--delay',-(i*.61%8)+'s');z.style.setProperty('--y',6+(i*31%86)+'%');z.style.setProperty('--a',.25+(i%6)*.03);z.style.setProperty('--s',(.38+(i%7)*.025)+'rem');z.style.setProperty('--dur',(7.2+(i%7)*.55)+'s')});
    const CH='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789?/:.-π';
    async function ticker(){const t='M4',st=performance.now();await new Promise(done=>{function a(now){const k=Math.min(2,Math.floor((now-st)/170));let o='';for(let i=0;i<2;i++)o+=i<k?t[i]:CH[(Math.floor(now/55)+i*9)%CH.length];m4.textContent=o;if(k<2)requestAnimationFrame(a);else{m4.textContent=t;done()}}requestAnimationFrame(a)})}
    async function compileBeat(){const nodes=[...co.querySelectorAll('i')],end=nodes.map(n=>n.dataset.final),st=performance.now();await new Promise(done=>{function a(now){const elapsed=now-st;nodes.forEach((n,i)=>{if(end[i]===' '){n.textContent='\u00a0';return}const lock=Math.max(0,Math.min(1,(elapsed-i*38)/760));n.textContent=lock>.78?end[i]:CH[(Math.floor(now/58)+i*7)%CH.length]});if(elapsed<1450)requestAnimationFrame(a);else{nodes.forEach((n,i)=>n.textContent=end[i]===' '?'\u00a0':end[i]);done()}}requestAnimationFrame(a)});co.classList.add('live');await sleep(950);co.classList.remove('live')}
    return async()=>{if(!(await waitForTarget(m4,3000)))return;cur.classList.add('m4current','show');await ticker();await sleep(650);if(await waitForTarget(co))await compileBeat();await sleep(500);if(await waitForTarget(ret)){ret.classList.add('live');await sleep(1750);ret.classList.remove('live')}await sleep(550);if(await waitForTarget(gl)){gl.classList.add('live');await sleep(4200);gl.classList.remove('live')}};
  }

  function start(){
    if(d.getElementById('foreword-target-choreography'))return;
    validate();const marker=d.createElement('meta');marker.id='foreword-target-choreography';d.head.appendChild(marker);
    const run1=setupPage1(),run2=setupPage2(),p3=setupPage3(),run4=setupPage4(p3.cur);
    (async()=>{await run1();await run2();await p3.run();await run4()})().catch(err=>{const badge=d.querySelector('.version-badge');if(badge)badge.textContent=`CHOREO FAIL · ${err.message}`;console.error('[THE GOOD BOOK] foreword choreography',err)});
  }
  w.HouseBook?start():w.addEventListener('house:ready',start,{once:true});
})();
